version: 2
jobs:
  build:
    working_directory: ~/exomiser
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: exomiser-{{ checksum "pom.xml" }}
#      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: exomiser-{{ checksum "pom.xml" }}
      - run: mvn install